### PR TITLE
new: 2B2T Queue HUD Element

### PR DESCRIPTION
**Pull request by ToxicAven**
Messy 3 AM Code, but it works

**Describe the pull**
Adds a new HUD Element, showing the 2B2T Queue Status. This currently uses an experimental API, Planned to be ready for production use within the week.

**Describe how this pull is helpful**
Partially Satisfies #1101

**Additional context**
Messy 3 AM Code, but it works. Definitely needs cleaned up.

### CODE REVIEW

**Comment by iBuyMountainDew** [comment]
Who's making this API? Can we trust in its reliability like we would with the `2b2t.dev` API?

**Comment by ToxicAven** [comment]
> 
> 
> Who's making this API? Can we trust in its reliability like we would with the `2b2t.dev` API?

Yes, this API is developed and maintained by tycrek#0001, and uses a method that allows multiple accounts to constantly provide data to the API, including priority data without the account having priority queue, making it more reliable than LoLritters Priority API.

**Comment by iBuyMountainDew** [comment]
Sounds good, I'll test properly in a little bit

**Review by l1ving — APPROVED** [review]
Thanks

**Pull request merged**
