### PR TITLE
Removed Forgelin

### PR DESCRIPTION
**Pull request by iBuyMountainDew**
- Completely removed Forgelin as it is not necessary and only serves to increase jar size.
~ Edited `build.gradle` to remove clutter.

Making this PR to request testing on you guys' machines, just in case yknow?

### CODE REVIEW

**Comment by dominikaaaa** [comment]
You do realize the reason we added forgelin was because kotlin doesn't work outside a developer environment?

**Comment by iBuyMountainDew** [comment]
It does though.

**Comment by dominikaaaa** [comment]
since when????

**Comment by iBuyMountainDew** [comment]
¯\_(ツ)_/¯ dk, I'll try testing on older versions of Forge, just in case it's a Forge update somehow.

**Comment by dominikaaaa** [comment]
I'm not sure why dewy requested you review this specific pull, you're not familiar with this code lol. Thanks anyways, I'll test this in a few minutes

**Pull request merged**
