### PR TITLE
[enhancement] Rendering with VBOs

### PR DESCRIPTION
**Pull request by Xiaro**
Asynchronous rendering with VBOs

### CODE REVIEW

**Comment by nopjmp** [comment]
Any specific areas that should be tested? I have a variety of GPUs I can test on.

**Comment by l1ving** [comment]
Modules such as search and storageesp with different types of blocks at max settings would be helpful to test, I think. Along with ESP in shader mode

**Comment by nopjmp** [comment]
Seems to be at least 20FPS better on my hardware while debugging without Optifine. More consistent and smooth FPS outside of that and feels less stuttery, but I'll continue more testing on actual servers instead of singleplayer where everything is tied together.

**Comment by Xiaro** [comment]
> Seems to be at least 20FPS better on my hardware while debugging without Optifine. More consistent and smooth FPS outside of that and feels less stuttery, but I'll continue more testing on actual servers instead of singleplayer where everything is tied together.

It isn't being used by any modules rn so it has literally no effect 🗿

**Comment by Xiaro** [comment]
> Any specific areas that should be tested? I have a variety of GPUs I can test on.

"Draft"

**Pull request closed without merging**
