### PR TITLE
[feature] Add manual mode to automine.

### PR DESCRIPTION
**Pull request by scorbett123**
**Describe the pull**
Adds a manual mode to automine. 

**Describe how this pull is helpful**
This means that it just mines the block one is facing at, not using baritone.

### CODE REVIEW

**Comment by l1ving** [comment]
> /build/sources/main/kotlin/me/zeroeightsix/kami/module/modules/misc/AutoMine.kt: (74, 20): Cannot access 'sendClickBlockToController': it is private in 'Minecraft'

You need to make an accessor for this, use the example which is already used for right clicks. 

https://github.com/kami-blue/client/blob/bd291d249eab04276ba6e8422ed53607e83dbbf4/src/main/java/me/zeroeightsix/kami/mixin/client/accessor/AccessorMinecraft.java#L25

**Comment by scorbett123** [comment]
I have done that however can't test it due to it being public in the first place for me.

**Comment by l1ving** [comment]
That would be because we removed our uses of access transformers, meaning you have to run setupDecompWorkspace to have the same stuff we do. If the travis build succeeds I'll review this later, thanks

**Comment by scorbett123** [comment]
Ok, thanks for explaining that.

**Comment by scorbett123** [comment]
Still doesn't build

**Comment by l1ving** [comment]
I'll fix it myself later then, or someone else will

**Comment by scorbett123** [comment]
It building finally.

**Review by l1ving — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
