### PR TITLE
Add license 1

### PR DESCRIPTION
**Pull request by cinnnnamondust**
**Describe the pull**
A clear and concise description of what the pull is for.

**Describe how this pull is helpful**
A clear description of why this should be merged

**Additional context**
Add any other context about the pull here.

### CODE REVIEW

**Comment by dominikaaaa** [comment]
???? what the fuck is this

**Comment by iBuyMountainDew** [comment]
man didnt understand the concept of "different repository" for his skid :rofl:

**Comment by Xiaro** [comment]
🐒

**Comment by humboldt123** [comment]
Lmfao did he skid it and forget to make a new repo?? ;m moment

**Pull request closed without merging**
