### PR TITLE
Update to auto excuse. 

### PR DESCRIPTION
**Pull request by natan515**
Pretty sure its completly wrong and if u could point out my mistakes would be nice (;

### CODE REVIEW

**Review by l1ving — CHANGES_REQUESTED** [review]
I don't see the point of any of this

**Comment by natan515** [comment]
It was more to check if what i did was correct.

**Comment by l1ving** [comment]
Syntax is fine, but there isn't a point to adding this

**Comment by natan515** [comment]
Ok, I'm just happy its ok, thx.

**Pull request closed without merging**
