### PR TITLE
Kotlinized Player modules and fixed issues #983, #971

### PR DESCRIPTION
**Pull request by sourTaste000**
**Describe the pull**
Kotlinized Player modules.
Fixed issue #983 
Fixed issue #971 

**Describe how this pull is helpful**
Don't everybody love kotlin?
Fixed two issues

**Additional context**

- [x] Kotlinize TpsSync 
- [x] Fix issue #983
- [x] Fix issue #971

### CODE REVIEW

**Comment by dominikaaaa** [comment]
Umm I'll do the tps sync, you just need to switch the mixins to use the instance

**Comment by sourTaste000** [comment]
k

**Comment by sourTaste000** [comment]
I already tested AutoArmour and PacketLogger. Still works

**Comment by sourTaste000** [comment]
oops I don't know why this commit is here

**Comment by sourTaste000** [comment]
Fixed #983

**Comment by sourTaste000** [comment]
should i make another pr lol

**Comment by dominikaaaa** [comment]
no, that's fine

**Comment by sourTaste000** [comment]
bruh i will make another pr

**Comment by dominikaaaa** [comment]
why furnace??

**Comment by sourTaste000** [comment]
idk the name for anvil gui

**Comment by dominikaaaa** [comment]
no?? what lol

**Comment by dominikaaaa** [comment]
when I'm on a computer I'll fix it

**Comment by sourTaste000** [comment]
k

**Pull request merged**
