### PR TITLE
[enhancement] Add store option to ChestStealer.

### LINKED ISSUE #498: Add reverse option to ChestStealer
- [ ] With a reverse option
- [x] always steal 
- [x] button steal

### PR DESCRIPTION
**Pull request by scorbett123**
**Describe the pull**
Adds a store option to chest stealer.

**Describe how this pull is helpful**
It is sometimes useful.

**Additional context**
Closes #498.

### CODE REVIEW

**Review by l1ving — APPROVED** [review]

**Comment by scorbett123** [comment]
Wait, I created a pull request with no glaring format issues, something must be wrong.

**Comment by l1ving** [comment]
nah there's format issues, I was gonna fix it myself while testing

**Comment by scorbett123** [comment]
ah, you got me all exited.

**Comment by scorbett123** [comment]
Thanks.

**Comment by l1ving** [comment]
Just noticed the new store method was nearly identical, so I merged store and steal into 1 method

**Comment by l1ving** [comment]
Thanks!

**Pull request merged**
