### PR TITLE
offhandcrystal.java

### PR DESCRIPTION
**Pull request by 3817**
add it its based on offhandgap but isntead of putting a gapple in your offhand it puts a crystal and places it when the crystalaura is activated.

### CODE REVIEW

**Comment by 3817** [comment]
its from turok autooffhand gap you can read at the package thing on the top 
"package com.oldturok.turok.module.modules.combat;"

**Comment by iBuyMountainDew** [comment]
No. 

First of all, there's bloody syntax errors in this code (turok package and import MODULE_MANAGER). If you're gonna skid, at least make the code work.

I don't think we'll just be merging a file directly taken 1:1 from turok anyways, we can make this ourselves.

**Comment by cookiedragon234** [comment]
Did you unironically just copy paste an entire module into a new file 😹

**Comment by dominikaaaa** [comment]
I can't believe you just tried adding a file that you 1:1 pasted from an outdated kami skid, which wouldn't even work

**Comment by dominikaaaa** [comment]
Not to mention that AutoTotem already has this option, this code looks 1:1 to mine

**Comment by elan69** [comment]
become a better copy-paster :>

**Comment by dominikaaaa** [comment]
l o l

**Pull request closed without merging**
