### PR TITLE
Added priority to Aura

### PR DESCRIPTION
**Pull request by NobleSix-Is-God**
The Priority have 3 modes
Distance
Health
None

### CODE REVIEW

**Comment by NobleSix-Is-God** [comment]
hello I find I write something wrong at line 172
it should be 
if (target2 != null || !mc.player.isDead){
instead of 
if (target2 != null && !mc.player.isDead){

**Comment by dominikaaaa** [comment]
If you think it's wrong you can edit the file on your repo and it will update in the pull

**Comment by NobleSix-Is-God** [comment]
Okey Finished.

**Comment by dominikaaaa** [comment]
Give me a bit to review it, still on my phone

**Comment by iBuyMountainDew** [comment]
Works for me 👍

**Comment by dominikaaaa** [comment]
Looked at the code, could you clean this up? There's a lot of unneeded casting, your sort is extremely inefficient (you can use a lambda), it breaks the multi option, and line 122 is duplicated at 173, which you could've used a method for. Really, most of this intellij could tell you. Also, your calculate damage method will crash and throw an exception because you're trying to do .equals to `Setting`s, when you need to do `.getValue()` in order to get the enum values for a .equals comparison
I appreciate the contribution but you'd need to clean up the code first.

**Pull request closed without merging**
