### PR TITLE
Created Installer

### PR DESCRIPTION
**Pull request by humboldt123**
**Describe the pull**
I created an installer for when you double click the Kami Jar

**Describe how this pull is helpful**
Some people can't follow instructions

**Additional context**
bread (1/20th)

### CODE REVIEW

**Comment by humboldt123** [comment]
```
 compile group: "com.formdev", name:"flatlaf", version: "0.38" doesnt work
```
I forgot that there was a line I commented out in build.gradle oof

**Comment by dominikaaaa** [comment]
I believe that this is ready to merge. I'll merge this in the morning if @humboldt123 doesn't have any other changes to do

**Comment by humboldt123** [comment]
You can merge it now. If I have any UI changes I would have to do them tommorow as I am on my phone.

**Comment by dominikaaaa** [comment]
Oh I forgot I was gonna move the package name. I'll do that tomorrow

**Comment by dominikaaaa** [comment]
oh also for the last notify() it should include version

**Comment by humboldt123** [comment]
If I'm being honest, it could do with more images as well but I can do that tommorow.

**Pull request merged**
