### PR TITLE
Added Search module.

### LINKED ISSUE #495: Search blocks module
Pinned as this is a very requested module
Custom blocks is a must

### PR DESCRIPTION
**Pull request by wnuke**
Added a search module, highlights blocks in world based on their Minecraft map item colour.

`;set search add <BLOCKNAME>` adds a block to search, if player adds block air, it gets ignored. 
eg: `;set search add minecraft:log`

`;set search del <BLOCKNAME>` removes a block to search.
eg: `;set search del minecraft:log`

`;set search blocks [string]` lists or sets the entire list of blocks. 
eg: `;set search blocks` will return `minecraft:portal,minecraft:end_portal_frame,minecraft:bed,` unless the player has changed the block list.
`;set search blocks minecraft:log,minecraft:crafting_table` will overwrite the list with `minecraft:log,minecraft:crafting_table`.

NOTE: if player adds a none existant block it will show up in the search list but will be ignored.

EDIT: this resolves #495

### CODE REVIEW

**Comment by iBuyMountainDew** [comment]
Everything's fine and dandy. Great job, wnuke.

**Comment by wnuke** [comment]
Thanks!

**Comment by dominikaaaa** [comment]
I'm considering reverting this, because my fps is literally halved before I even add any blocks.

**Comment by iBuyMountainDew** [comment]
It's performed fine on my system, @wnuke have you experienced any performance problems when compared to a version without the Search module?

**Comment by dominikaaaa** [comment]
And I'd also prefer to have a proper command with autocomplete like xray does for adding and removing blocks.

**Comment by dominikaaaa** [comment]
I mean great work, but I rarely have performance issues with Minecraft and my fps is literally cut from 60 to 15-30 before I start adding blocks that will render.

**Comment by wnuke** [comment]
Hmm, I dont know how to do the auto complete, but I will look at x-ray, there are two functions for easily adding and removing blocks that are public

@iBuyMountainDew yeah, the latest commit mostly fixed performance, now it should be only 10% drop, before it was around 50-70% drop

@dominikaaaa you have performance issues?

**Comment by wnuke** [comment]
Oh right, if you have search enable on world load the game will lag for 5-10 seconds then it will go to normal.

**Comment by dominikaaaa** [comment]
To do the autocomplete you use the proper command system, see XRayCommand. 

And I do, it's literally unplayable. I'll try keeping it enabled for longer but I had it on for about a minute.

**Comment by iBuyMountainDew** [comment]
The fact that you are even mentioning FPS drops of >1% is alarming. I reckon this should be reverted until you can optimise the search module further, as clearly on some systems it's causing performance problems.

**Comment by wnuke** [comment]
Hmm, I did around 10 minutes of testing on my own computer, no problems but I can revert it until its sorted out, I guess I need testers with a variety of different systems.

**Comment by dominikaaaa** [comment]
My laptop specs aren't that horrible, it's not the best but it's what I would expect most people to be playing on (I'll be honest here, I've seen so many garbage systems from new players). 

I have an i7-5600U (4) with 4GB available RAM for MC.

**Comment by iBuyMountainDew** [comment]
I'm running Windows on a Ryzen 3 1300X, with a GTX 1050Ti as my GPU.

**Comment by wnuke** [comment]
hmm, I have i7-7000 with 4GB ram for mc and a radeon 560 pro, so i dont know why you are having problems, I am currently running my main minecraft instance with search and its working really well

**Comment by dominikaaaa** [comment]
I don't have a GUI, unlike either of you. I let Minecraft sit for about a minute with search enabled, and I was back to 60. Once I add (soul sand in this case) a single block to it I'm down to 10-20 fps, more commonly 10. Note, I have 0 issues with storage esp's rendering. 

If I leave it on my performance exponentially goes down, eventually hitting 1 fps. This definitely indicates a recursive performance problem. 
I appreciate the work you've done writing this but I'd need to performance issues to be fixed before adding it.

**Comment by wnuke** [comment]
Yeah, makes sense, but I am not having the performance issues, until I add a block that there is a lot of (endstone in this case) but if I have a normal search setting my performance gets better the more I play, I will try to fix any recursive things that are happening.

**Comment by dominikaaaa** [comment]
If there's a lot of that block I totally understand, every Search does that. But once I add a single block it drops. 

Note, I had to run the add command *twice* every time I tested because the first time it never worked.

**Pull request merged**
