### PR TITLE
Render modules update and bug fixes

### PR DESCRIPTION
**Pull request by Xiaro**
**Describe the pull**
- Rewrotes
1. Rewrote KamiTessellator
2. Rewrote Search
3. Rewrote ESP
4. Rewrote EyeFinder
5. Rewrote Tracer

- New
1. Added ESPRenderer
2. Added BreadCrumbs 
3. Added BreakingESP (Merged Breaking Warning)
4. Added SelectionHighlight
5. Added WaypointRender
6. Added spoof rotation option to Aura
7. Added option to disable Elytra Sounds to ElytraFlight

- Fix
1. Fixed AutoEat spams pausing baritone #1113 
2. Fixed ChunkFinder uses green in the End dimension #1100
3. Fixed Aura spams unpausing Baritone
4. Fixed Aura tps sync #1082 
5. Fixed ElytraFlight casuing crashes while above void #1090
6. Fixed ElytraFlight takeoff/landing not working in singleplayer (mfw using ElytraFlight in singleplayer)
7. Fixed Slider bar in GUI causing rendering issue (GUI gets brighter/darker)
8. Fixed opening GUI causing rendering issue (GUI gets brighter/darker)
9. Fixed StorageESP/ESP/Search not render correctly at worldborder

- Others
Kotlinized some events

**Describe how this pull is helpful**
- Rewrotes
1. Added drawOutline method #674. All drawing methods now use VBO to optimize perfomance. This should also fixes render module crashes with other client #769 (tests pending) 
2. Less bugs #980. Better performamce #819. Added max blocks and max distance #960 .
3. Replace rect mode with box mode, merged BoxESP, option to target all entity.
4. Also draws box at the entity looking at.
5. #671.

- New
1. Easier for others to add ESP rendering module
2. #949 
3. Same as Breaking Warning but draws a box to show the progress and tracer to the block
4. #195 
5. #1111 
6. Better than locking your view
7. Less annoying noise when afk flying in the background

**Additional context**
I will try to stop making big pr like this next time >.<

### CODE REVIEW

**Comment by sourTaste000** [comment]
39 commit but no conflict
how???????

**Comment by humboldt123** [comment]
Xirao is a magician

**Comment by sourTaste000** [comment]
mfw build failed

**Comment by dominikaaaa** [comment]
OOpsies

**Comment by dominikaaaa** [comment]
> e: /home/travis/build/kami-blue/client/build/sources/main/kotlin/me/zeroeightsix/kami/module/modules/render/Tracers.kt: (81, 45): Expecting an argument

Code error @Xiaro

**Pull request merged**
