### PR TITLE
impr: Copy NBT data to clipboard

### LINKED ISSUE #2119: `;nbt copy` subcommand to copy to clipboard, instead of to value
Currently users assume that `;nbt copy` will copy to clipboard. Have the existing `;nbt copy` renamed to `;nbt copydata`, and add descriptions for the subcommands, so it is more intuitive.

### PR DESCRIPTION
**Pull request by scorbett123**
closes #2119

Copies to clipboard and pastes from clipboard.

### CODE REVIEW

**Review by l1ving — CHANGES_REQUESTED** [review]
Please use the `org.kamiblue.commons.utils.SystemUtils` to reduce boilerplate code, and I believe the copying / pasting needs to be run on a separate thread to prevent stuttering

**Comment by nopjmp** [comment]
Clipboard manipulation can happen on the main thread as long as it is not excessively being called each frame.

**Comment by l1ving** [comment]
Suppose so, I was thinking more in the sense of some massive nbt data, because some things can get pretty big

**Review by l1ving — APPROVED** [review]

**Comment by l1ving** [comment]
Thanks!

**Pull request merged**
