### PR TITLE
Update TemporaryPauseProcess.java (#864) (leijurv)

### PR DESCRIPTION
**Pull request by leijurv**
**Describe the pull**
A clear and concise description of what the pull is for.

**Describe how this pull is helpful**
A clear description of why this should be merged

**Additional context**
Add any other context about the pull here.

### CODE REVIEW

**Comment by iBuyMountainDew** [comment]
Why not :p

**Comment by cookiedragon234** [comment]
Describe the pull
A clear and concise description of what the pull is for.

Describe how this pull is helpful
A clear description of why this should be merged

Additional context
Add any other context about the pull here.

**Comment by leijurv** [comment]
dEsCrIbE ThE PuLl a cLeAr aNd cOnCiSe dEsCrIpTiOn oF WhAt tHe pUlL Is fOr.  dEsCrIbE HoW ThIs pUlL Is hElPfUl a cLeAr dEsCrIpTiOn oF WhY ThIs sHoUlD Be mErGeD  aDdItIoNaL CoNtExT AdD AnY OtHeR CoNtExT AbOuT ThE PuLl hErE.

**Comment by cookiedragon234** [comment]
Descwibe the puww
A cweaw and concise descwiption of what the puww is fow.

Descwibe how this puww is hewpfuw
A cweaw descwiption of why this shouwd be mewged

Additionyaw context
Add any othew context about the puww hewe

**Comment by leijurv** [comment]
dEsCwIbE ThE PuWw a cWeAw aNd cOnCiSe dEsCwIpTiOn oF WhAt tHe pUwW Is fOw.  dEsCwIbE HoW ThIs pUwW Is hEwPfUw a cWeAw dEsCwIpTiOn oF WhY ThIs sHoUwD Be mEwGeD  aDdItIoNyAw cOnTeXt aDd aNy oThEw cOnTeXt aBoUt tHe pUwW HeWe

**Comment by dominikaaaa** [comment]
😳😳

**Comment by iBuyMountainDew** [comment]
__***dEsCwIbE ThE PuWw a cWeAw aNd cOnCiSe dEsCwIpTiOn oF WhAt tHe pUwW Is fOw. dEsCwIbE HoW ThIs pUwW Is hEwPfUw a cWeAw dEsCwIpTiOn oF WhY ThIs sHoUwD Be mEwGeD aDdItIoNyAw cOnTeXt aDd aNy oThEw cOnTeXt aBoUt tHe pUwW HeWe***__

**Pull request merged**
