### PR TITLE
refactor: Rewrite the installer

### PR DESCRIPTION
**Pull request by scorbett123**
Rewrite the installer, visually and functionally it is almost exactly the same, except now it is in kotlin.

I believe that something is messing it up sometimes when I test it, however I think that it is a problem with my internet connection not the code, so if people can test this to make sure of that, it would be appreciated. 

Some aspects are based off of the original installer, however others have been completely rewritten such as the testing for an existing version.

### CODE REVIEW

**Comment by l1ving** [comment]
I removed `.toRegex()` on `"/"` in `getJarName()` because I don't see the point, unless you can explain why it was a regex

**Comment by scorbett123** [comment]
uh, no, a mistake on my behalf, not realising that it didn't need to be a regex.

**Comment by scorbett123** [comment]
Thanks for the changes.

**Comment by l1ving** [comment]
Couple of things, the warning icon isn't really correct here, and the jar detection does not work...
image

**Comment by l1ving** [comment]
I fixed the icons but I don't know quite why the jar detection isn't working.

**Comment by scorbett123** [comment]
> I fixed the icons but I don't know quite why the jar detection isn't working.

It seems to work for me, I don't know why it wouldn't for you.

**Comment by l1ving** [comment]
```
mods % rr
/home/mika/.config/minecraft/mods
mods % pwd
/home/bella/.local/share/multimc/instances/KAMI Blue/.minecraft/mods
mods % java -jar wheee.jar 
Running the KAMI Blue 2.02.xx-dev Installer
Exception in thread "main" java.net.UnknownHostException: home
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:961)
        at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:923)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1018)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1004)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
        at java.base/sun.net.www.protocol.jar.URLJarFile.retrieve(URLJarFile.java:212)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:74)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
        at org.kamiblue.client.installer.Installer.getKamiJars(Installer.kt:161)
        at org.kamiblue.client.installer.Installer.main(Installer.kt:59)
Download started
Download finished.
```

**Comment by l1ving** [comment]
Added some debug:
```
Jar url: jar:file://home/mika/.minecraft/mods/unused!/
Jar url real path: file://home/mika/.minecraft/mods/unused!/
```

image

It looks like it's trying to open the folder as a file... lol

**Comment by scorbett123** [comment]
Currently it just uses the preset values in [folder utils](https://github.com/kami-blue/client/blob/master/src/main/kotlin/org/kamiblue/client/util/filesystem/FolderUtils.kt).

**Comment by scorbett123** [comment]
Sorry, I thought I had a check in there, however obviously it got removed at some point, will add that now.

**Comment by l1ving** [comment]
I added a directory check and I get this now
```
Running the KAMI Blue 2.02.xx-dev Installer
Jar url: jar:file://home/mika/.minecraft/mods/wheee.jar!/
Jar url real path: file://home/mika/.minecraft/mods/wheee.jar!/
Exception in thread "main" java.net.UnknownHostException: home
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:961)
        at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:923)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1018)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1004)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
        at java.base/sun.net.www.protocol.jar.URLJarFile.retrieve(URLJarFile.java:212)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:74)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
        at org.kamiblue.client.installer.Installer.getKamiJars(Installer.kt:164)
        at org.kamiblue.client.installer.Installer.main(Installer.kt:59)
```

One thing to note about just returning if it's a dir... if someone has mods in the `~/.minecraft/mods/1.12.2` folder it will try to load before your KAMI Blue, so we should also check for KAMI Blue jars inside that folder

**Comment by scorbett123** [comment]
So check every subfolder under that folder? I don't know what is causing that issue, and unfortunately can't check, however I imagine that it is OS specific, and therefore I won't be able to reproduce it.

**Comment by l1ving** [comment]
> So check every subfolder under that folder?

No, only `~/.minecraft/mods/1.12.2` because that is the only other place you can load KAMI Blue from, as it's a 1.12.2 only forge mod

> I don't know what is causing that issue, and unfortunately can't check

https://stackoverflow.com/a/24612422

Surely there has to be another way to check resources of jars?

**Comment by scorbett123** [comment]
> Surely there has to be another way to check resources of jars?

You probably know better than me, the only other one that you could do would be to change it to a zip file, and unzip that, however I imagine that that would be slow, and I have no idea where to even get started with doing that.

**Comment by l1ving** [comment]
Well yea, but the error I'm getting says it's trying to open the path as a hostname... which really doesn't make sense. I guess I can look into doing it otherwise or go back to checking jar names

**Review by l1ving — CHANGES_REQUESTED** [review]
Looked into it, still not sure about the jar checking. Will try another method tomorrow

**Comment by scorbett123** [comment]
Maybe we can use something like [this](https://github.com/kami-blue/bot-kt/blob/master/src/main/kotlin/org/kamiblue/botkt/plugin/PluginLoader.kt#L20), I will test it out now.

**Comment by scorbett123** [comment]
I can't seem to get that to work, if you can then we can use it, however maybe just surrounding it in a try catch, that should mean that if it ever errors we can just use name checking.

**Comment by l1ving** [comment]
I will try to get this working without the try catch.

**Review by l1ving — APPROVED** [review]
I can't find a better way to do it than how we do it now,

**Comment by l1ving** [comment]
Thanks!

**Comment by scorbett123** [comment]
Thanks for checking if there was another way.

**Pull request merged**
