### PR TITLE
Easy change your FOV above minecrafts maximum

### PR DESCRIPTION
**Pull request by LittleDraily**
**Describe the pull**
With this module you can change your FOV above minecrafts standard

**Describe how this pull is helpful**
I found it helpfull and easy

### CODE REVIEW

**Comment by dominikaaaa** [comment]
Kami blue already has this feature, it's called zoom.

**Comment by LittleDraily** [comment]
Oh epic

**Comment by iBuyMountainDew** [comment]
obamahack moment

**Comment by LittleDraily** [comment]
Obamahack moment? lol

**Comment by elan69** [comment]
im gonna say the n word

**Pull request closed without merging**
