### PR TITLE
Fix freecam chunk rendering

### LINKED ISSUE #1633: Freecam is having some problems loading chunks
**Describe the bug**
When u go on freecam chunks just become laggy, hard to explain, watch my vid for a straight explaining.

**To Reproduce**

1. Go to 'freecam on kamiblue'
2. Click on 'activate it.'
3. look at ur player as he moves
4. See how chunks don't load compare to other utility mods freecam

**Expected behavior**
It should just load everything in 5 chunks from the player, like every other freecam.

**Screenshots**
https://www.youtube.com/watch?v=BkJTD-YUfR0&feature=youtu.be

**Additional context**
Pretty annoying normally, the only reason I use pyro freecam.

### PR DESCRIPTION
**Pull request by zeroeightysix**
Closes #1633 + small cleanup regarding the (incredibly funny) entity ID

### CODE REVIEW

**Comment by l1ving** [comment]
Shouldn't the renderChunksMany be set the other way around? You want to render extra chunks in freecam?

**Comment by zeroeightysix** [comment]
> Shouldn't the renderChunksMany be set the other way around? You want to render extra chunks in freecam?

Nope. Look at the implementation - this is a severe case of pathetic forge mappings.

**Review by l1ving — APPROVED** [review]
Thanks, looks good to me!

**Comment by Xiaro** [comment]
Why onEnable :moyai: that is gonna break after disconnect

**Comment by zeroeightysix** [comment]
> Why onEnable moyai that is gonna break after disconnect

unless you're doing weird stuff, the field (and, thus, the rendering) stays the same regardless of whether or not you're connected to a server

**Pull request merged**
