### PR TITLE
Fix Spammer doesn't support cyrillic symbols 

### PR DESCRIPTION
**Pull request by suretic**
https://github.com/kami-blue/client/issues/766

---
name: issue #766 
about: Fix for issue #766 
---

### CODE REVIEW

**Comment by dominikaaaa** [comment]
Would you mind making these changes for LoginMessage and ChatFilter? @suretic

**Comment by suretic** [comment]
sure

**Comment by dominikaaaa** [comment]
thanks!

**Comment by suretic** [comment]
https://prnt.sc/sgbspz
Is LoginMessage supposed to be working? When I try to connect to a server I get this error with and without my changes

**Comment by dominikaaaa** [comment]
What's the log? Honestly open a new bug report tbh

**Comment by suretic** [comment]
Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(Util.java:48)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:298)
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(Util.java:47)
	... 9 more
00:53:31.074
Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(Util.java:48)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147240_a(NetHandlerPlayClient.java:1876)
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:58)
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:11)
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(Util.java:47)
	... 9 more
00:53:31.075
Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(Util.java:48)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_175101_a(NetHandlerPlayClient.java:1532)
	at net.minecraft.network.play.server.SPacketServerDifficulty.func_148833_a(SourceFile:25)
	at net.minecraft.network.play.server.SPacketServerDifficulty.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(Util.java:47)
	... 9 more

**Comment by dominikaaaa** [comment]
Make a bug report

**Pull request merged**
