### PR TITLE
[feature] Ear-System when?

### PR DESCRIPTION
**Pull request by FriedrichM**
### **Ear-System**

In my opinion a proper _Ear-System_ is an integral ingredient to a good and  well polished utility mod.
The user will feel anxious when switching to this client if they can't find a way to enable his beloved **EARS**, 
and ultimately they will consider buying Non-Open-Source-Clients to fill the hole in their heart
that the missing _Ear-System_ has created.

It can be considered incompetent or unprofessional to not have an option in ones client 
that gives the user full control over their appearance in the game!

Some would even say it restrict their right to express their sexuality.
We can no longer afford to be part of the problem that separates our community and promotes hatred.

I will not continue to tolerate these outdated principles and i demand change to happen soon!

deadmau

### CODE REVIEW

**Comment by l1ving** [comment]
good issue

**Review by l1ving — COMMENTED** [review]
the syntax was so correct I had to actually spend a minute wondering if the code worked lol

**Comment by natan515** [comment]
what is it??? lol after this kami blue would become the best utility mod, all the paid client have no chance now.

**Comment by spide-r** [comment]
why is this help wanted lol

**Comment by l1ving** [comment]
very important pull

**Comment by natan515** [comment]
living said that she might add it if u would make it optional, I would like u to do it pls lol

**Comment by FriedrichM** [comment]
feel free the branch is still up. i dont care

**Comment by natan515** [comment]
Ol, i will try.

**Pull request closed without merging**
