### PR TITLE
Added logpos and listpos commands. Also improved CoordsLogger.

### PR DESCRIPTION
**Pull request by wnuke**
Added a command to log a position with a name (;logpos [name]) and another to list and or search logged positions (;listpos [searchterm]) according to #713 

Improved CoordsLogger by adding a setting for only logging coordinates on death or to log them repeatedly after a delay, also moved it from hidden to experimental.

### CODE REVIEW

**Comment by dominikaaaa** [comment]
I would prefer the commands to be one command, for example `;pos list filter` and `;pos save name`. Let me know if you want me to do that.

**Comment by wnuke** [comment]
That's, fine, one less file, I will combine them.

**Comment by dominikaaaa** [comment]
Thanks

**Comment by wnuke** [comment]
`;pos list filter` "filter" being the search term?

**Comment by dominikaaaa** [comment]
Correct, but if no filter is supplied it lists all of them

**Comment by wnuke** [comment]
Ok, will do.

**Comment by sourTaste000** [comment]
need to solve the conflicts tho

**Comment by wnuke** [comment]
Fixed merge confilcts.

**Comment by dominikaaaa** [comment]
Thanks. I'll try to find time to review this later today.

**Comment by dominikaaaa** [comment]
@wnuke um, I think I'm going to have to fuck up the commit history, sorry about that. I'll fix the merge conflicts myself.

**Comment by wnuke** [comment]
Alright, no problem

**Comment by cookiedragon234** [comment]
image

**Comment by dominikaaaa** [comment]
Wait fuck why does it say 70 files changed. I found time to review this today but can you fix it @wnuke

**Comment by cookiedragon234** [comment]
Also please tell me how you edited 70 files for this commit 🤣

**Comment by iBuyMountainDew** [comment]
lmao this reverts all of the kotlinization

**Comment by dominikaaaa** [comment]
It's because I force pushed it 🙃

**Comment by wnuke** [comment]
I have no idea on why it changes so many files, it should add 2 delete 1 and modify another

**Comment by iBuyMountainDew** [comment]
It's a merging issue to deal with the switch from java to kotlin, try merging master into your branch before PRing your branch into master.

**Comment by wnuke** [comment]
Hmm i had done that, twice now because it got out of date by nearly a week and had conflicts

**Comment by iBuyMountainDew** [comment]
Welp, it's time to do it again ._.

**Comment by dominikaaaa** [comment]
Yea, sorry about that. Could you make a new pull request? I'm sorry this took so long to review, and the fact you caught me in the middle of converting to Kotlin.

**Comment by wnuke** [comment]
Alright, will do

**Pull request closed without merging**
