### PR TITLE
Added Franky module

### PR DESCRIPTION
**Pull request by humboldt123**
Reverse engineered from Impact Client

**Describe the pull**
Added Franky module from Impact.

**Describe how this pull is helpful**
Franky is a feature in Impact that is not in KAMI

**Additional context**
Does exactly what you think it does.

### CODE REVIEW

**Comment by iBuyMountainDew** [comment]
good meme but a silly pr

**Comment by sourTaste000** [comment]
why is there big rat

**Comment by humboldt123** [comment]
https://kamiblue.org/backdoored

**Comment by humboldt123** [comment]
The election was called a few days late however @iBuyMountainDew is free to merge.

**Comment by Xiaro** [comment]
Repo deleted :woeis:

**Pull request closed without merging**
