### PR TITLE
[cleanup] ChunkEvent, NoRender, NewChunks

### PR DESCRIPTION
**Pull request by Xiaro**
Removed bunch of verbose code in NewChunks and fixed crash caused by ConcurrentModificationException.
The "SaveNewChunk" was removed because it doesn't do anything beside spamming files with coords and timestamp, making the the code unreadable and hard to maintain. Also I don't think anyone uses it anyways.

### CODE REVIEW

**Comment by l1ving** [comment]
I know people do use the saving, including IronException who's been a long time contributor. I'd rather not remove features without providing an alternative, it can be removed and replaced with a plugin later.

**Comment by Xiaro** [comment]
> I know people do use the saving, including IronException who's been a long time contributor. I'd rather not remove features without providing an alternative, it can be removed and replaced with a plugin later.

No, it is not saving the actual chunk. Just some coords and timestamp

**Comment by l1ving** [comment]
I know, that's what I meant. I accidentally messed it up in a commit and he noticed like the next day lol

**Comment by nopjmp** [comment]
> including IronException who's been a long time contributor
If he's still around, maybe we can collaborate on his usage and propose a solution before releasing this PR.

I was thinking having a sqlite database would be better instead of just a log file, or moving it into a "CoordLogger" module so it's a single purpose module instead of tacked onto NewChunks.

**Comment by l1ving** [comment]
There's already a coordlogger module, a newchunks option would fit better I think. Also using sqlite or at least csv (like packetlogger does now) would be better I think. Thoughts @IronException?

**Comment by l1ving** [comment]
Talked on Discord, decided to remove this and readd it as a CoordsLogger option or plugin in the future instead

**Pull request merged**
