### PR TITLE
Add KamiMoji

### LINKED ISSUE #794: Emoji support
https://github.com/2b2t-Utilities/emoji-api

Waiting for documentation from tiger

### PR DESCRIPTION
**Pull request by iBuyMountainDew**
Closes #794 

Possible improvements could include some kind of autocomplete or something similar to the gray preview text with commands.

### CODE REVIEW

**Comment by dominikaaaa** [comment]
I'll review this later

**Comment by iBuyMountainDew** [comment]
I'm confident that this is mergeable.

**Comment by dominikaaaa** [comment]
mfw merged without testing or review :roll_eyes:

**Comment by zeroeightysix** [comment]
this is the way do to collaborative open source

**Comment by dominikaaaa** [comment]
definitely :+1:

**Comment by humboldt123** [comment]
the way to do it is to roll a dice on weather or not to merge

**Pull request merged**
