### PR TITLE
[feature] BoatFly

### PR DESCRIPTION
**Pull request by MrMrMr-MC**
buttfly bypass 4 ncp

**Describe the pull**
Boatfly Bypass

**Describe how this pull is helpful**
Boatfly Bypass

**Additional context**
Boatfly Bypass

### CODE REVIEW

**Comment by natan515** [comment]
With your first 2 words: boat bypass, I was already convinced it's good. Thank you so much for adding it!

**Comment by Doogie13** [comment]
The jar doesnt build

**Comment by ezBot03** [comment]
This might be a bit picky, but line 34 it says obat, and I think it's supposed to spell boat.

**Comment by Doogie13** [comment]
I'll try editing it and seeing if it builds

**Comment by l1ving** [comment]
Won't fix. Several issues with this 

- Code style is violating literally every major standard there is for Java / Kotlin
- This doesn't even build 
- This doesn't build because it's a Salbug module just pasted in without being ported
- 2b2t has patched this anyways 

Thanks for your contribution, please fix these issues in a new pull I'd you'd like this merged.

**Pull request closed without merging**
